# Generated by Django 2.2.4 on 2019-08-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190807_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='assign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todos.Arrow'),
            preserve_default=False,
        ),
    ]
